data:
  raw: data/raw/heart_clean.csv
  processed: "data/processed/heart_processed.csv"

training:
  test_size: 0.2
  random_state: 42
  cv_splits: 5
  model_path: "models/best_model.pkl"

model:
  xgb:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
